// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Taller1PIS.Migrations
{
    [DbContext(typeof(PosContext))]
    [Migration("20230520182526_initialCommit")]
    partial class initialCommit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Producto", b =>
                {
                    b.Property<int>("Idproducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idproducto");

                    b.Property<int>("Codigo")
                        .HasColumnType("int")
                        .HasColumnName("codigo");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("nombre");

                    b.Property<int>("Precio")
                        .HasColumnType("int")
                        .HasColumnName("precio");

                    b.HasKey("Idproducto")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Codigo" }, "codigo_UNIQUE")
                        .IsUnique();

                    b.ToTable("producto", "POS");
                });

            modelBuilder.Entity("Venta", b =>
                {
                    b.Property<int>("Idventa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idventa");

                    b.Property<double>("Correlativo")
                        .HasColumnType("double")
                        .HasColumnName("correlativo");

                    b.Property<DateTime?>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<TimeSpan?>("Hora")
                        .HasColumnType("time")
                        .HasColumnName("hora");

                    b.Property<string>("RutCliente")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("rutCliente");

                    b.HasKey("Idventa")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Correlativo" }, "correlativo_UNIQUE")
                        .IsUnique();

                    b.ToTable("venta", "POS");
                });

            modelBuilder.Entity("VentaProducto", b =>
                {
                    b.Property<int>("IdventaProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idventa_producto");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int")
                        .HasColumnName("cantidad");

                    b.Property<int?>("Idproducto")
                        .HasColumnType("int")
                        .HasColumnName("idproducto");

                    b.Property<int?>("Idventa")
                        .HasColumnType("int")
                        .HasColumnName("idventa");

                    b.Property<int>("Precio")
                        .HasColumnType("int")
                        .HasColumnName("precio");

                    b.HasKey("IdventaProducto")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Idproducto" }, "idproducto_idx");

                    b.HasIndex(new[] { "Idventa" }, "idventa_idx");

                    b.ToTable("venta_producto", "POS");
                });

            modelBuilder.Entity("VentaProducto", b =>
                {
                    b.HasOne("Producto", "IdproductoNavigation")
                        .WithMany("VentaProductos")
                        .HasForeignKey("Idproducto")
                        .HasConstraintName("idproducto");

                    b.HasOne("Venta", "IdventaNavigation")
                        .WithMany("VentaProductos")
                        .HasForeignKey("Idventa")
                        .HasConstraintName("idventa");

                    b.Navigation("IdproductoNavigation");

                    b.Navigation("IdventaNavigation");
                });

            modelBuilder.Entity("Producto", b =>
                {
                    b.Navigation("VentaProductos");
                });

            modelBuilder.Entity("Venta", b =>
                {
                    b.Navigation("VentaProductos");
                });
#pragma warning restore 612, 618
        }
    }
}
